### ISSUE TITLE
unmet dependencies

### ISSUE THREAD

**Issue by marcel-more** [fmgarage/ft-fms-docker#16]
Just tried to do a fresh install with the latest Script version from this repo:
- finished with 'error while installing filemaker server' while trying filemaker-server-19.6.2.201-amd64.deb
- finished with 'error while installing filemaker server' while trying filemaker-server_19.4.2.204_amd64.deb

Perhaps error log is helpful for any improvements?
see below

-----

Starting install inside fmsinstall container

timezone from host: Europe/Berlin 

Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'filemaker-server:amd64' instead of '/root/build/**filemaker-server-19.6.2.201-amd64.deb**'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 filemaker-server:amd64 : Depends: apache2-bin:amd64 but it is not installable
                          Depends: nginx:amd64 but it is not installable
                          Depends: logrotate:amd64 but it is not installable
                          Depends: firewalld:amd64 but it is not installable
                          Depends: odbcinst1debian2:amd64 but it is not installable
                          Depends: openjdk-11-jre:amd64 but it is not installable
                          Depends: policycoreutils:amd64 but it is not installable
                          Depends: sysstat:amd64 but it is not installable
                          Depends: zlib1g:amd64 but it is not installable
                          Depends: libaio1:amd64 but it is not installable
                          Depends: libantlr3c-3.4-0:amd64 but it is not installable
                          Depends: libavahi-client3:amd64 but it is not installable
                          Depends: libboost-chrono1.71.0:amd64 but it is not installable
                          Depends: libboost-system1.71.0:amd64 but it is not installable
                          Depends: libboost-thread1.71.0:amd64 but it is not installable
                          Depends: libbz2-1.0:amd64 but it is not installable
                          Depends: libc++1-12:amd64 but it is not installable
                          Depends: libcurl4:amd64 but it is not installable
                          Depends: libdjvulibre21:amd64 but it is not installable
                          Depends: libetpan20:amd64 but it is not installable
                          Depends: libevent-2.1-7:amd64 but it is not installable
                          Depends: libexpat1:amd64 but it is not installable
                          Depends: libfontconfig1:amd64 but it is not installable
                          Depends: libfreetype6:amd64 but it is not installable
                          Depends: libgomp1:amd64 but it is not installable
                          Depends: libheif1:amd64 but it is not installable
                          Depends: libicu66:amd64 but it is not installable
                          Depends: libilmbase24:amd64 but it is not installable
                          Depends: libjpeg-turbo8:amd64 but it is not installable
                          Depends: liblqr-1-0:amd64 but it is not installable
                          Depends: liblzma5:amd64 but it is not installable
                          Depends: libodbc1:amd64 but it is not installable
                          Depends: libomp5-12:amd64 but it is not installable
                          Depends: libopenexr24:amd64 but it is not installable
                          Depends: libpam0g:amd64 but it is not installable
                          Depends: libpng16-16:amd64 but it is not installable
                          Depends: libsasl2-2:amd64 but it is not installable
                          Depends: libtiff5:amd64 but it is not installable
                          Depends: libuuid1:amd64 but it is not installable
                          Depends: libvpx6:amd64 but it is not installable
                          Depends: libwebpdemux2:amd64 but it is not installable
                          Depends: libwebpmux3:amd64 but it is not installable
                          Depends: libxml2:amd64 but it is not installable
                          Depends: libxpm4:amd64 but it is not installable
                          Depends: libxslt1.1:amd64 but it is not installable
                          Depends: libcurl3-gnutls:amd64 but it is not installable
E: Unable to correct problems, you have held broken packages.
error while installing filemaker server
build not successful
stopping & removing build container ...
fmsinstall
fmsinstall

-----

Starting install inside fmsinstall container

timezone from host: Europe/Berlin 

Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'filemaker-server:amd64' instead of '/root/build/**filemaker-server_19.4.2.204_amd64.deb**'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 filemaker-server:amd64 : Depends: sysstat:amd64 but it is not installable
                          Depends: libaio1:amd64 but it is not installable
                          Depends: libicu60:amd64 but it is not installable
                          Depends: libuuid1:amd64 but it is not installable
                          Depends: libevent-2.1-6:amd64 but it is not installable
                          Depends: zlib1g:amd64 but it is not installable
                          Depends: libsasl2-2:amd64 but it is not installable
                          Depends: libfontconfig1:amd64 but it is not installable
                          Depends: libgomp1:amd64 but it is not installable
                          Depends: libcurl4:amd64 but it is not installable
                          Depends: firewalld:amd64 but it is not installable
                          Depends: apache2-bin:amd64 but it is not installable
                          Depends: libavahi-client3:amd64 but it is not installable
                          Depends: libvpx5:amd64 but it is not installable
                          Depends: libxpm4:amd64 but it is not installable
                          Depends: libxslt1.1:amd64 but it is not installable
                          Depends: openjdk-11-jre:amd64 but it is not installable
                          Depends: libodbc1:amd64 but it is not installable
                          Depends: odbcinst1debian2:amd64 but it is not installable
                          Depends: policycoreutils:amd64 but it is not installable
                          Depends: libbz2-1.0:amd64 but it is not installable
                          Depends: libfreetype6:amd64 but it is not installable
                          Depends: libtiff5:amd64 but it is not installable
                          Depends: libpng16-16:amd64 but it is not installable
                          Depends: libjpeg-turbo8:amd64 but it is not installable
                          Depends: liblzma5:amd64 but it is not installable
                          Depends: libwebpmux3:amd64 but it is not installable
                          Depends: libwebpdemux2:amd64 but it is not installable
                          Depends: libexpat1:amd64 but it is not installable
                          Depends: libxml2:amd64 but it is not installable
                          Depends: liblqr-1-0:amd64 but it is not installable
                          Depends: libdjvulibre21:amd64 but it is not installable
                          Depends: libopenexr22:amd64 but it is not installable
                          Depends: libilmbase12:amd64 but it is not installable
E: Unable to correct problems, you have held broken packages.
error while installing filemaker server
build not successful
stopping & removing build container ...
fmsinstall
fmsinstall

**Comment by sk-gara** [comment]
I think that is because of the M1 being an ARM CPU. As I understand, Docker Desktop on Apple Silicon pulls arm64 images by default, if available.
Also, FMS 19.6 needs Ubuntu 20.04.
You could test by editing the file **build/Dockerfile** at line 4:

from
`FROM ubuntu:18.04`

to
`FROM amd64/ubuntu:18.04`

and then try to install FMS **19.4.**

For version 19.6, there is a new Dockerfile with some changes to the dependencies published by Claris. Also, I am not sure if the installation with Ubuntu:20.04 works at all - see the discussion from last week:
#15

**Comment by marcel-more** [comment]
Thanks for the hint!
I had to repeat a fresh installation for several times as the Ubuntu package threw some errors and waited for about an hour without any progress during installation. The third try was finally successful for the Ubuntu AMD part, but the FileMaker Server installation still failed...

please refer to log below:

-----

Starting install inside fmsinstall container

timezone from host: Europe/Berlin 

Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'filemaker-server' instead of '/root/build/filemaker-server_19.4.2.204_amd64.deb'
The following NEW packages will be installed:
  filemaker-server
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/344 MB of archives.
After this operation, 1718 MB of additional disk space will be used.
Get:1 /root/build/filemaker-server_19.4.2.204_amd64.deb filemaker-server amd64 19.4.2.204 [344 MB]
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package filemaker-server.
(Reading database ... 14058 files and directories currently installed.)
Preparing to unpack .../filemaker-server_19.4.2.204_amd64.deb ...
=== Perform pre-installation of filemaker-server_19.4.2.204 (install)
    Assisted installation template is /root/build/Assisted Install.txt
    Environment variable FM_ASSISTED_INSTALL is set to /root/build/Assisted Install.txt.
    Use the configuration specified in /root/build/Assisted Install.txt for assisted Installation.
    Deployment type: Claris FileMaker Server primary machine.
    Use default license certificate.
    Claris FileMaker Server primary machine is being installed by root to run as fmserver of fmsadmin group.
    Create fmsadmin group.
    Create fmserver user in fmsadmin group.
Unpacking filemaker-server (19.4.2.204) ...
Setting up filemaker-server (19.4.2.204) ...
=== Perform post-installation of filemaker-server_19.4.2.204 (configure) 
    Assisted installation template is /root/build/Assisted Install.txt
    /opt/FileMaker/FileMaker Server/Database Server/Extensions/OpenSSL/RootCA/apple_corporate_root_ca.pem not existed.
/var/lib/dpkg/info/filemaker-server.postinst: line 1457: setfacl: command not found
    Set up core dump location at /var/crash.
    Configure Claris FileMaker Server primary machine installation...
    Install default license certificate.
    Create a default Claris FileMaker Server primary machine configuration with English locale.
    Set up WebDirect preferences.
    Set up Web Publishing Engine preferences.
    Start firewalld service service...
FirewallD is not running
    Open HTTP connection port 80...
    Open HTTPS connection port 443...
    Open Claris FileMaker Server primary machine connection port 5003...
    Open ODBC connection port 2399...
    Open Claris FileMaker Server primary machine connection port 16002...
    Enable and start HTTP server service.
    Enable Claris FileMaker Server primary machine service.
    Start Claris FileMaker Server primary machine service.
    Claris FileMaker Server primary machine service has started.
    Wait 2 seconds for the session token...
    Wait 2 seconds for the session token...
    Wait 2 seconds for the session token...
    Wait 2 seconds for the session token...
    Wait 2 seconds for the session token...
    Wait 2 seconds for the session token...
    Wait 2 seconds for the session token...
    Wait 2 seconds for the session token...
    Wait 2 seconds for the session token...
    Wait 2 seconds for the session token...
    Wait 2 seconds for the session token...
    Wait 2 seconds for the session token...
    Error! Cannot get a session token.
N: Download is performed unsandboxed as root as file '/root/build/filemaker-server_19.4.2.204_amd64.deb' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)
no certificate found, proceeding...

  --  default fmsadmin settings... 
Error: 10502 (Host unreachable)
error while fmsadmin securefilesonly
build not successful
stopping & removing build container ...
fmsinstall
fmsinstall

**Comment by sk-gara** [comment]
Quick try: I switched the Docker Desktop filesystem from virtioFS back to gRPC FUSE and a 19.4 installation in Ubuntu 18 went through with no errors. Would you care to try that on your end? I am assuming your setting is on virtioFS as well, is it though?

**Comment by marcel-more** [comment]
Thanks for feedback. No luck so far... Docker setting are still on gRPC FUSE. Same error persists: "Error: 10502 (Host unreachable)". Perhaps something wrong with the network settings? I give up for now. Will have another try when setup for 19.6 is officially ready.

**Comment by sk-gara** [comment]
I think i had that too before cleaning up everything. Did you see that I pushed an update yesterday?
If not already done so, remove all containers and images left over, so that a new build will run from scratch. My attempts where finally successful yesterday, but I only have an Intel iMac here.
Other than that I don't know. There where no changes to the network settings since 19.4 or was there? But since it worked in my case i don't think that's the problem.

**Comment by marcel-more** [comment]
Thanks for the update! Tried again from scratch. But error persists. Do I need to install a proper SSL certificate perhaps?

**Comment by sk-gara** [comment]
No, should not be necessary. Do you still have these 2 errors?

```
/opt/FileMaker/FileMaker Server/Database Server/Extensions/OpenSSL/RootCA/apple_corporate_root_ca.pem not existed.
/var/lib/dpkg/info/filemaker-server.postinst: line 1457: setfacl: command not found
```

I don't think I had them.

**Comment by marcel-more** [comment]
Just had another try with a fresh install, but still no luck.
This time there have been other errors (see below).
As Claris itself gave a statement in it's own Docker guideline, that FMS would not run on Apple Silicon, I suppose that this could be the main reason for the failing installation?
Will there be a Docker script for FMS on Linux for a M1 machine in the future? As I found out, there are ARM-Versions of Ubuntu available. Should by technically possible to provide a solution, isn't it?

> Some packages could not be installed. This may mean that you have
> requested an impossible situation or if you are using the unstable
> distribution that some required packages have not yet been created
> or been moved out of Incoming.
> The following information may help to resolve the situation:
> 
> The following packages have unmet dependencies:
>  filemaker-server : Depends: libicu60 but it is not installable
>                     Depends: libevent-2.1-6 but it is not installable
>                     Depends: libvpx5 but it is not installable
>                     Depends: libopenexr22 but it is not installable
>                     Depends: libilmbase12 but it is not installable
> E: Unable to correct problems, you have held broken packages.
